public class anurag {
    public static void main(String[] args) {
        System.out.println("anurag handique");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("virus x has executed\n your program files\nyour computer is now hacked\nshut down");
        System.out.println("thanks from anurag handique");
    }
}

